on:
    workflow_call:
      inputs:
        environmentType:
          required: true
          type: string
      secrets:
        AZURE_CLIENT_ID:
          required: true
        AZURE_TENANT_ID:
          required: true
        AZURE_SUBSCRIPTION_ID:
          required: true
jobs:
    say-hello:
        runs-on: ubuntu-latest
        steps:
        - run: |
            echo Hello ${{ inputs.environmentType }}!